engines:
    eslint:
        enabled: true
        checks:
            global-require:
                enabled: false
    csslint:
        enabled: true
    scsslint:
        enabled: true
ratings:
    paths:
    - "**/*"
exclude_paths:
- demo/**/*
- dist/**/*
